from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    path('',views.vistaIndex, name='inicio'),
    path('Octal/',views.vistaOctal, name='octal'),
    path('Decimal/',views.vistaDecimal, name='decimal'),
    path('Binario/',views.vistaBinaria, name='binario'),
    path('Hexadecimal/',views.vistaHexadecimal, name='hexadecimal'),
    path('resultadoOctal/',views.vistaResultadoOctal, name='resultadoOctal'),
    path('resultadoBinario/',views.vistaResultadoBinario, name='resultadoBinario'),
    path('resultadoDecimal/',views.vistaResultadoDecimal, name='resultadoDecimal'),
    path('resultadoHexadecimal/',views.vistaResultadoHexadecimal, name='resultadoHexadecimal'),
    path('iee/', include('estandarIEE.urls')),
    path('ecu/', include('ecuaciones.urls')),
    path('derivadas/', views.vistaDerivadas, name='derivadas'),
    path('derivadasSolucion/',views.vistaSolucion, name='derivadasSolucion'),
    path('secante/', views.vistaSecante, name='secante'),
    path('secanteSolucion/',views.secanteSolucion, name='secanteSolucion'),
    path('decimal32/', views.vistaDecimal32, name='decimal32'),
    path('decimalABit32/',views.vistaDecimalBit32, name='decimalABit32'),
    path('decimal64/', views.vistaDecimal64, name='decimal64'),
    path('decimalABit64/',views.vistaDecimalBit64, name='decimalABit64'),
    path('graficar/', views.vistaGraficar, name='graficar'),
    path('newtonR/',views.vistaNewton, name='newtonR'),
    path('newton/',views.vistaNew, name='newton'),
    path('raiz/',views.raiznew, name='raiz'),
    path('bisecion/',views.vistabi, name='bisecion'),
    path('bisecionr/',views.bisecionr, name='bisecionr'),
    path('raizr/',views.vistaraicez_pro, name='raizr'),
    path('posicion/',views.vistaposicion, name='posicion'),
    path('posicionr/',views.vistaponew, name='posicionr'),
    path('trapecio/',views.vistatrapecio, name='trapecio'),
    path('trapecioR/',views.TrapeNew, name='trapecioR'),
    path('rectangulos/',views.vistaRectangulos, name='rectangulos'),
    path('rectangulosSolucion/',views.vistaRectangulosSolucion, name='solucionRectangulos'),
    path('SimpsonSolucion/',views.vistaSimpsonSolucion, name='SimpsonSolucion'),
    path('Simpson/',views.vistaSimpson, name='Simpson'),
    path('carlo/',views.vistaCarlo, name='carlo'),
    path('carloSolucion/',views.vistaCarloSolucion, name='solucionCarlo'),
    path('vistamatrixSolucion/',views.vistamatrixSolucion, name='vistamatrixSolucion'),
    path('vistaMatrixcomplejaSolucion/',views.vistaMatrixcomplejaSolucion, name='vistaMatrixcomplejaSolucion'),
    path('matrix/', views.get_digits, name='get_digits'),
    path('operaciones/', views.operaciones, name='operaciones'),
    path('operaciones2/', views.operaciones2, name='operaciones2'),
    path('operaciones3/', views.operaciones3, name='operaciones3'),
    path('mostrar_form_ajuste_de_curvas/', views.mostrar_form_ajuste_de_curvas, name='mostrar_form_ajuste_de_curvas'),
    path('resolver_ajuste_curvas/', views.resolver_ajuste_curvas, name='resolver_ajuste_curvas'),
    path('resolver_ecuaciones_lineales/', views.resolver_ecuaciones_lineales, name='resolver_ecuaciones_lineales'),
    path('to_float/', views.to_float, name='to_float'),
    path('to_matriz/', views.to_matriz, name='to_matriz'),
    path('ordenar_arreglo/', views.ordenar_arreglo, name='ordenar_arreglo'),
    path('limpiar_respuesta/', views.limpiar_respuesta, name='limpiar_respuesta'),
    path('determinar_func/', views.determinar_func, name='determinar_func'),
    path('hallar_media_y/', views.hallar_media_y, name='hallar_media_y'),
    path('resolver_lineal/', views.resolver_lineal, name='resolver_lineal'),
    path('hallar_st/', views.hallar_st, name='hallar_st'),
    path('hallar_sr/', views.hallar_sr, name='hallar_sr'),
    path('sumatoria/', views.sumatoria, name='sumatoria'),
    path('sumatoria_y/', views.sumatoria_y, name='sumatoria_y'),
    path('resultado_y/', views.resultado_y, name='resultado_y'),
    path('solucionar_ajuste_curvas/', views.solucionar_ajuste_curvas, name='solucionar_ajuste_curvas'),
    path('retornar_func/', views.retornar_func, name='retornar_func'),
    path('Gauss/', views.get_digits2, name='get_digits2')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
